Resources:
  LawrenceHueAppClientIdA2E29F07:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString: {}
      Name: LawrenceHueApp/CLIENT_ID
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppClientId/Resource
  LawrenceHueAppClientSecret9EA09E41:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString: {}
      Name: LawrenceHueApp/CLIENT_SECRET
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppClientSecret/Resource
  LawrenceHueAppAuthFunctionServiceRole2F68B227:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppAuthFunction/ServiceRole/Resource
  LawrenceHueAppAuthFunctionAEE687DC:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035S3Bucket1E974DC1
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035S3VersionKey090F629A
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035S3VersionKey090F629A
      Handler: auth.handler
      Role:
        Fn::GetAtt:
          - LawrenceHueAppAuthFunctionServiceRole2F68B227
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          CLIENT_ID:
            Fn::Join:
              - ""
              - - "{{resolve:secretsmanager:"
                - Ref: LawrenceHueAppClientIdA2E29F07
                - :SecretString:::}}
          CLIENT_SECRET:
            Fn::Join:
              - ""
              - - "{{resolve:secretsmanager:"
                - Ref: LawrenceHueAppClientSecret9EA09E41
                - :SecretString:::}}
    DependsOn:
      - LawrenceHueAppAuthFunctionServiceRole2F68B227
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppAuthFunction/Resource
      aws:asset:path: asset.8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035
      aws:asset:property: Code
  LawrenceHueAppApi42C53374:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: LawrenceHueAppApi
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Resource
  LawrenceHueAppApiCloudWatchRoleBF260B7C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/CloudWatchRole/Resource
  LawrenceHueAppApiAccount5F925CF0:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - LawrenceHueAppApiCloudWatchRoleBF260B7C
          - Arn
    DependsOn:
      - LawrenceHueAppApi42C53374
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Account
  LawrenceHueAppApiDeployment6AC23E0527e5d99936fd77bf076ffd57d52e1b6a:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: LawrenceHueAppApi42C53374
      Description: Automatically created by the RestApi construct
    DependsOn:
      - LawrenceHueAppApiproxyANY7B91A82C
      - LawrenceHueAppApiproxyAB783C35
      - LawrenceHueAppApiANYCC864C92
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Deployment/Resource
  LawrenceHueAppApiDeploymentStageprod5A99F346:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: LawrenceHueAppApi42C53374
      DeploymentId:
        Ref: LawrenceHueAppApiDeployment6AC23E0527e5d99936fd77bf076ffd57d52e1b6a
      StageName: prod
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/DeploymentStage.prod/Resource
  LawrenceHueAppApiproxyAB783C35:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - LawrenceHueAppApi42C53374
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: LawrenceHueAppApi42C53374
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Default/{proxy+}/Resource
  LawrenceHueAppApiproxyANYApiPermissionLawrenceHueAppStackLawrenceHueAppApi44AA412AANYproxyB6EBF743:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LawrenceHueAppAuthFunctionAEE687DC
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-west-2:661272765443:"
            - Ref: LawrenceHueAppApi42C53374
            - /
            - Ref: LawrenceHueAppApiDeploymentStageprod5A99F346
            - /*/*
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Default/{proxy+}/ANY/ApiPermission.LawrenceHueAppStackLawrenceHueAppApi44AA412A.ANY..{proxy+}
  LawrenceHueAppApiproxyANYApiPermissionTestLawrenceHueAppStackLawrenceHueAppApi44AA412AANYproxyE97BBAA5:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LawrenceHueAppAuthFunctionAEE687DC
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-west-2:661272765443:"
            - Ref: LawrenceHueAppApi42C53374
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Default/{proxy+}/ANY/ApiPermission.Test.LawrenceHueAppStackLawrenceHueAppApi44AA412A.ANY..{proxy+}
  LawrenceHueAppApiproxyANY7B91A82C:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: LawrenceHueAppApiproxyAB783C35
      RestApiId:
        Ref: LawrenceHueAppApi42C53374
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:eu-west-2:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - LawrenceHueAppAuthFunctionAEE687DC
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Default/{proxy+}/ANY/Resource
  LawrenceHueAppApiANYApiPermissionLawrenceHueAppStackLawrenceHueAppApi44AA412AANYB35C4A97:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LawrenceHueAppAuthFunctionAEE687DC
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-west-2:661272765443:"
            - Ref: LawrenceHueAppApi42C53374
            - /
            - Ref: LawrenceHueAppApiDeploymentStageprod5A99F346
            - /*/
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Default/ANY/ApiPermission.LawrenceHueAppStackLawrenceHueAppApi44AA412A.ANY..
  LawrenceHueAppApiANYApiPermissionTestLawrenceHueAppStackLawrenceHueAppApi44AA412AANY0C62F3F7:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LawrenceHueAppAuthFunctionAEE687DC
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-west-2:661272765443:"
            - Ref: LawrenceHueAppApi42C53374
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Default/ANY/ApiPermission.Test.LawrenceHueAppStackLawrenceHueAppApi44AA412A.ANY..
  LawrenceHueAppApiANYCC864C92:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - LawrenceHueAppApi42C53374
          - RootResourceId
      RestApiId:
        Ref: LawrenceHueAppApi42C53374
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:eu-west-2:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - LawrenceHueAppAuthFunctionAEE687DC
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: LawrenceHueAppStack/LawrenceHueAppApi/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.45.0,@aws-cdk/assets=1.45.0,@aws-cdk/aws-apigateway=1.45.0,@aws-cdk/aws-cloudwatch=1.45.0,@aws-cdk/aws-ec2=1.45.0,@aws-cdk/aws-events=1.45.0,@aws-cdk/aws-iam=1.45.0,@aws-cdk/aws-kms=1.45.0,@aws-cdk/aws-lambda=1.45.0,@aws-cdk/aws-logs=1.45.0,@aws-cdk/aws-s3=1.45.0,@aws-cdk/aws-s3-assets=1.45.0,@aws-cdk/aws-sam=1.45.0,@aws-cdk/aws-secretsmanager=1.45.0,@aws-cdk/aws-sqs=1.45.0,@aws-cdk/aws-ssm=1.45.0,@aws-cdk/cdk-assets-schema=1.45.0,@aws-cdk/cloud-assembly-schema=1.45.0,@aws-cdk/core=1.45.0,@aws-cdk/cx-api=1.45.0,@aws-cdk/region-info=1.45.0,jsii-runtime=node.js/v14.1.0
Parameters:
  AssetParameters8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035S3Bucket1E974DC1:
    Type: String
    Description: S3 bucket for asset "8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035"
  AssetParameters8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035S3VersionKey090F629A:
    Type: String
    Description: S3 key for asset version "8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035"
  AssetParameters8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035ArtifactHash717FCA39:
    Type: String
    Description: Artifact hash for asset "8d48090de6fffc041e80c23fbe8ec7d75b121eb6998c55a4bd469609a4d27035"
Outputs:
  LawrenceHueAppApiEndpoint9311B505:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: LawrenceHueAppApi42C53374
          - .execute-api.eu-west-2.
          - Ref: AWS::URLSuffix
          - /
          - Ref: LawrenceHueAppApiDeploymentStageprod5A99F346
          - /

